# Generated by Django 3.1.6 on 2021-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='num_periods',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='degreesubject',
            name='period',
            field=models.PositiveIntegerField(),
        ),
    ]
